import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Schedule Call | Thank You</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="topper">
          <div className="top-container">
            <a href="tel:+918000161161">
              <img
                src="https://www.hyperlinkinfosystem.com/assets/frontend_assets/img/ind-flag.svg"
                alt="india"
              />{" "}
              +91 8000 161161
            </a>
            <a href="tel:+13097914105">
              <img
                src="https://www.hyperlinkinfosystem.com/assets/frontend_assets/img/us-flag.svg"
                alt="usa"
              />{" "}
              +1 309 791 4105
            </a>
            <a href="tel:+442081338639">
              <img
                src="https://www.hyperlinkinfosystem.com/assets/frontend_assets/img/uk-flag.svg"
                alt="uk"
              />{" "}
              +44 20 8133 8639
            </a>
          </div>
          <div className="top-buttons">
            <a href="https://www.hyperlinkinfosystem.com/press-releases.html">
              Press Release
            </a>
            <a href="https://www.hyperlinkinfosystem.com/our-portfolio">
              Our Fresh Work
            </a>
            <a
              // style="background-color: #4842A8 !important;color: #fff !important;"
              href="https://www.hyperlinkinfosystem.com/schedule-a-call"
            >
              Schedule Call
            </a>
          </div>
        </section>
        <section className="menubar-container">
          <div>
            <Image
              height="80"
              width="120"
              src="https://www.hyperlinkinfosystem.com/assets/frontend_assets/img/logo.svg"
            />
          </div>
          <div>
            <ul className="bar-list">
              {["Company", "Services", "Hire Developers"].map((data, index) => (
                <li className="bar-list-item" key={index}>
                  <p>{data}</p>
                  <span>
                    <svg
                      height="10px"
                      width="10px"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 320 512"
                      style={{
                        marginLeft: "3px",
                        marginBottom: "3px",
                      }}
                    >
                      <path d="M182.6 470.6c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-9.2-9.2-11.9-22.9-6.9-34.9s16.6-19.8 29.6-19.8H288c12.9 0 24.6 7.8 29.6 19.8s2.2 25.7-6.9 34.9l-128 128z" />
                    </svg>
                  </span>
                </li>
              ))}
              <li className="bar-list-item">
                <p>Case Study</p>
              </li>
              <li className="bar-list-item">
                <p>Resources</p>
                <span>
                  <svg
                    height="10px"
                    width="10px"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 320 512"
                    style={{
                      marginLeft: "3px",
                      marginBottom: "3px",
                    }}
                  >
                    <path d="M182.6 470.6c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-9.2-9.2-11.9-22.9-6.9-34.9s16.6-19.8 29.6-19.8H288c12.9 0 24.6 7.8 29.6 19.8s2.2 25.7-6.9 34.9l-128 128z" />
                  </svg>
                </span>
              </li>
              <li className="bar-list-item">
                <p>Contact Us</p>
              </li>
              <li
                style={{
                  padding: "16px",
                  boxShadow: "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px",
                  borderRadius: "30px",
                  fontWeight: "600",
                  cursor: "pointer",
                  marginLeft: "10px",
                  color: "#797a7a",
                }}
                className="bar-list-item"
              >
                <p>Get A Free Quote</p>
              </li>
            </ul>
          </div>
        </section>
        <section className="schedule-details">
          <div>
            <h1 className="main-title">Schedule Call</h1>
          </div>
          <div className="calender-container">
            <iframe
              src="https://calendly.com/hyperlinkinfo/introduction-call-with-hyperlink-infosystem-clone?embed_domain=www.hyperlinkinfosystem.com&amp;embed_type=Inline"
              width="100%"
              height="100%"
              frameborder="0"
            ></iframe>
          </div>

          <h2>Social</h2>
        </section>
        <section className="social-things">
          <div>
            <div className="social-items-container">
              <div className="ti-subti">
                <h5 className="title">Social Media</h5>
                <p className="subtitle">
                  Don&apos;t Miss To Follow Us On Our Social Networks Accounts.
                </p>
              </div>
              <div>
                <ul className="social-icons-container">
                  <li>
                    <a href="https://www.facebook.com/Hyperlink-infosystem-140449209446270/">
                      <img
                        src="https://www.hyperlinkinfosystem.com/assets/frontend_assets/img/fb-icon.svg"
                        alt="facebook"
                      />
                    </a>
                  </li>
                  <li>
                    <a href="https://twitter.com/hyperlinkinfo">
                      <img
                        src="https://www.hyperlinkinfosystem.com/assets/frontend_assets/img/tw-icon.svg"
                        alt="twitter"
                      />
                    </a>
                  </li>
                  <li>
                    <a href="https://www.instagram.com/hyperlink_infosystem/">
                      <img
                        src="https://www.hyperlinkinfosystem.com/assets/frontend_assets/img/insta-icon.svg"
                        alt="instagram"
                      />
                    </a>
                  </li>
                  <li>
                    <a href="https://www.linkedin.com/company/hyperlinkinfosystem">
                      <img
                        src="https://www.hyperlinkinfosystem.com/assets/frontend_assets/img/in-icon.svg"
                        alt="linkedin"
                      />
                    </a>
                  </li>
                  <li>
                    <a href="https://www.youtube.com/channel/UC1-3xlMsMK-47ew6WfbLqsQ">
                      <img
                        src="https://www.hyperlinkinfosystem.com/assets/frontend_assets/img/yt-icon.svg"
                        alt="youtube"
                      />
                    </a>
                  </li>
                  <li>
                    <a href="https://topappdevelopmentcompanies.com">
                      <img
                        src="https://www.hyperlinkinfosystem.com/assets/frontend_assets/img/tp-icon.svg"
                        height="35"
                        width="35"
                        alt="topappdevelopmentcompanies"
                      />
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section className="footer-container">
          <div className="template">
            <img
              className="img1"
              height="130px"
              width="97px"
              src="https://www.hyperlinkinfosystem.com/assets/frontend_assets/img/pattern-1.svg"
            />
            <img
              className="img2"
              height="260px"
              width="320px"
              src="https://www.hyperlinkinfosystem.com/assets/frontend_assets/img/pattern2.svg"
            />
            <div>
              <h1 className="title">Let&apos;s Create Big Stories Together</h1>
              <h1 className="subtitle">
                Mobile is in our nerves. We don&apos;t just build apps, we
                create brand. Choosing us will be your best decision
              </h1>
            </div>
            <div className="get-quote-button">
              <a
                href="https://www.hyperlinkinfosystem.com/contact.html"
                title=""
              >
                Get A Quote{" "}
                <img
                  src="https://www.hyperlinkinfosystem.com/assets/frontend_assets/img/arrow-right-white.svg"
                  alt=""
                />
              </a>
            </div>
          </div>
          <div className="main-foot">
            <div className="foot-shades">
              <div className="foot-part">
                <h1 className="shader">About</h1>
                <h2>About</h2>
                <div>
                  <div className="foot-list">
                    <a
                      href="https://www.hyperlinkinfosystem.com/who-we-are.html"
                      className="foot-item"
                    >
                      Who We Are
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/career.html"
                      className="foot-item"
                    >
                      Career
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/events.html"
                      className="foot-item"
                    >
                      Events
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/services.html"
                      className="foot-item"
                    >
                      Services
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/industries"
                      className="foot-item"
                    >
                      Industries
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/case-study"
                      className="foot-item"
                    >
                      Case Study
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/our-portfolio"
                      className="foot-item"
                    >
                      Portfolio
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/sitemap.html"
                      className="foot-item"
                    >
                      Sitemap
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/contact.html"
                      className="foot-item"
                    >
                      Contact Us
                    </a>
                  </div>
                </div>
              </div>
              <div className="foot-part">
                <h1 className="shader">Mobile</h1>
                <h2>Mobile</h2>
                <div>
                  <div className="foot-list">
                    <a
                      href="https://www.hyperlinkinfosystem.com/android-app-development-india.htm"
                      className="foot-item"
                    >
                      Android Apps
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/iphone-application-development-india.htm"
                      className="foot-item"
                    >
                      iPhone Apps
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/hybrid-app-development"
                      className="foot-item"
                    >
                      Hybrid Apps
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/flutter-app-development.htm"
                      className="foot-item"
                    >
                      Flutter
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/react-native-app-development.htm"
                      className="foot-item"
                    >
                      React Native
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/kotlin-app-development.htm"
                      className="foot-item"
                    >
                      Kotlin
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/ionic-app-development.htm"
                      className="foot-item"
                    >
                      Ionic
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/swift-development"
                      className="foot-item"
                    >
                      Swift
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/xamarin-app-development"
                      className="foot-item"
                    >
                      Xamrin
                    </a>
                  </div>
                </div>
              </div>
              <div className="foot-part">
                <h1 className="shader">Web</h1>
                <h2>Web</h2>
                <div>
                  <div className="foot-list">
                    <a
                      href="https://www.hyperlinkinfosystem.com/php-web-application-development.htm"
                      className="foot-item"
                    >
                      PHP
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/java-development-service.htm"
                      className="foot-item"
                    >
                      Java
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/python-web-development.htm"
                      className="foot-item"
                    >
                      Python
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/wordpress-development-india.htm"
                      className="foot-item"
                    >
                      Wordpress
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/drupal-development-india.htm"
                      className="foot-item"
                    >
                      Drupal
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/laravel-development.htm"
                      className="foot-item"
                    >
                      Laravel
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/codeigniter-development.htm"
                      className="foot-item"
                    >
                      CodeIgniter
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/cakephp-development-india.htm"
                      className="foot-item"
                    >
                      CakePHP
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/typescript"
                      className="foot-item"
                    >
                      TypeScript
                    </a>
                  </div>
                </div>
              </div>
              <div className="foot-part">
                <h1 className="shader">Ecommerce</h1>
                <h2>Ecommerce</h2>
                <div>
                  <div className="foot-list">
                    <a
                      href="https://www.hyperlinkinfosystem.com/magento-development-india.htm"
                      className="foot-item"
                    >
                      Magento
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/shopify-development"
                      className="foot-item"
                    >
                      Shopify
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/ubercart-development-india.htm"
                      className="foot-item"
                    >
                      Ubercart
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/prestashop.htm"
                      className="foot-item"
                    >
                      Prestashop
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/cs-cart-development.htm"
                      className="foot-item"
                    >
                      CS Cart
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/virtuemart-development-india.htm"
                      className="foot-item"
                    >
                      VirtueMart
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/bigcommerce.htm"
                      className="foot-item"
                    >
                      BigCommerce
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/woocommerce-development"
                      className="foot-item"
                    >
                      WooCommerce
                    </a>
                  </div>
                </div>
              </div>
              <div className="foot-part">
                <h1 className="shader">AI</h1>
                <h2>AI & ML</h2>
                <div>
                  <div className="foot-list">
                    <a
                      href="https://www.hyperlinkinfosystem.com/text-to-speech"
                      className="foot-item"
                    >
                      Text to Speech
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/business-intelligence"
                      className="foot-item"
                    >
                      Business Intelligence
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/data-forecasting"
                      className="foot-item"
                    >
                      Data Forecasting
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/natural-language-processing"
                      className="foot-item"
                    >
                      Natural Language Processing
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/data-analytics"
                      className="foot-item"
                    >
                      Data Analytics
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/object-recognition"
                      className="foot-item"
                    >
                      Object Recognition
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/sentimental-analysis"
                      className="foot-item"
                    >
                      Sentimental Analysis
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/alexa-skills-development.htm"
                      className="foot-item"
                    >
                      Alexa Skills Development
                    </a>
                  </div>
                </div>
              </div>
              <div className="foot-part">
                <h1 className="shader">IoT</h1>
                <h2>IoT & Embedded</h2>
                <div>
                  <div className="foot-list">
                    <a
                      href="https://www.hyperlinkinfosystem.com/iot-app-development"
                      className="foot-list"
                    >
                      IoT App
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/embedded-software"
                      className="foot-list"
                    >
                      Embedded Software
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/iot-hardware-prototyping"
                      className="foot-list"
                    >
                      IoT Hardware Prototyping
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/iot-dashboard-and-analytics"
                      className="foot-list"
                    >
                      IoT Dashboard and Analytics
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/smart-home-home-automation"
                      className="foot-list"
                    >
                      Smart Home - Home Automation
                    </a>
                  </div>
                </div>
              </div>
              <div className="foot-part">
                <h1 className="shader">Blockchain</h1>
                <h2>Blockchain</h2>
                <div>
                  <div className="foot-list">
                    <a
                      href="https://www.hyperlinkinfosystem.com/cryptocurrency-wallet-development"
                      className="foot-item"
                    >
                      Wallet
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/cryptocurrency-exchange-development"
                      className="foot-item"
                    >
                      Exchange
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/ethereum-app-development.htm"
                      className="foot-item"
                    >
                      Ethereum
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/hyperledger-blockchain-development.htm"
                      className="foot-item"
                    >
                      Hyperledger
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/smart-contracts-development.htm"
                      className="foot-item"
                    >
                      Smart Contracts
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/private-blockchain-development.htm"
                      className="foot-item"
                    >
                      Private Blockchains
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/nft-marketplace-development-company"
                      className="foot-item"
                    >
                      NFT Marketplace
                    </a>
                  </div>
                </div>
              </div>
              <div className="foot-part">
                <h1 className="shader">Game</h1>
                <h2>Game</h2>
                <div>
                  <div className="foot-list">
                    <a
                      href="https://www.hyperlinkinfosystem.com/unity3d-game-development.htm"
                      className="foot-item"
                    >
                      Unity 3D
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/unreal-engine-game-development"
                      className="foot-item"
                    >
                      Unreal Engine
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/augmented-reality-app-development-company.htm"
                      className="foot-item"
                    >
                      Augmented Reality
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/virtual-reality-mobile-game-application-development-company-oculus-vr.htm"
                      className="foot-item"
                    >
                      Virtual Reality
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/casual-game-development.htm"
                      className="foot-item"
                    >
                      Casual Games
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/metaverse-development-company"
                      className="foot-item"
                    >
                      Metaverse
                    </a>
                  </div>
                </div>
              </div>
              <div className="foot-part">
                <h1 className="shader">Salesforce</h1>
                <h2>Salesforce</h2>
                <div>
                  <div className="foot-list">
                    <a
                      href="https://www.hyperlinkinfosystem.com/salesforce-development.htm"
                      className="foot-item"
                    >
                      Salesforce Development
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/salesforce-consulting.htm"
                      className="foot-item"
                    >
                      Salesforce Consulting
                    </a>
                    <a
                      href="https://www.hyperlinkinfosystem.com/salesforce-implementation.htm"
                      className="foot-item"
                    >
                      Salesforce Implementation
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
